# Data Profiling

## Load and Preview Data

##### In this section, we load the raw CSV files and preview the first few rows
to understand the structure and content of the datasets.

In [1]:
from itertools import product
from pathlib import Path
import pandas as pd
import numpy as np

In [4]:
path = Path("raw_data")
customers_df =pd.read_csv(path/'customers.csv')
products_df =pd.read_csv(path/'products.csv')
orders_df = pd.read_csv(path/'orders.csv')

In [5]:
customers_df.head()

,customer_id,name,email,age,city,created_at
0,1450,Melissa Estrada,melissa.667@gmail.com,71.0,Birmingham,2023-04-29
1,7000,Laura Kim,laura.7653@gmail.com,60.0,Chicago,2023-06-10
2,1830,Adam Willis,adam.9749@example.com,32.0,Giza,2025-06-03
3,19,Matthew Foster,matthew.7934@hotmail.com,64.0,Barcelona,2026-05-15
4,7560,Kelly Brooks,kelly.1296@gmail.com,38.0,Osaka,2024-11-02

In [6]:
products_df.head()

   product_id              product_name     category   price   stock
0         153       Eco-Friendly Webcam  Electronics  627.79  4470.0
1         418   Heavy Duty Coffee Beans      Grocery   489.2  3461.0
2         904   Ultra Bluetooth Speaker  Electronics  605.87  3394.0
3         373              Ultra Hoodie     Clothing  740.43  2821.0
4         685  Rechargeable Car Charger   Automotive  122.32  4890.0

In [7]:
orders_df.head()

   order_id  customer_id  product_id quantity  order_date
0     82086       6213.0       878.0        0  2026-02-11
1     11334       7997.0        31.0       10  2025-11-22
2     18441       9355.0       781.0        6  2022-04-07
3     30531       6685.0        84.0        6  2024-11-23
4     82609       2933.0       435.0        1  2025-12-10

## Dataset Overview

In [9]:
customers_df.shape

(10000, 6)

In [12]:
customers_df.columns

Index(['customer_id', 'name', 'email', 'age', 'city', 'created_at'], dtype='str')

In [14]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10000 non-null  int64
 1   name         9952 non-null   str
 2   email        9951 non-null   str
 3   age          9903 non-null   float64
 4   city         9944 non-null   str
 5   created_at   10000 non-null  str
dtypes: float64(1), int64(1), str(4)
memory usage: 468.9 KB

In [10]:
products_df.shape

(1000, 5)

In [11]:
orders_df.shape

(100000, 5)

In [15]:
products_df.columns

Index(['product_id', 'product_name', 'category', 'price', 'stock'], dtype='str')

In [16]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1000 non-null   int64
 1   product_name  1000 non-null   str
 2   category      996 non-null    str
 3   price         985 non-null    str
 4   stock         996 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 39.2 KB

In [17]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   order_id     100000 non-null  int64
 1   customer_id  99431 non-null   float64
 2   product_id   99440 non-null   float64
 3   quantity     99406 non-null   str
 4   order_date   99397 non-null   str
dtypes: float64(2), int64(1), str(2)
memory usage: 3.8 MB

## Missing Values

In [19]:
customers_df.isna().sum()

customer_id     0
name           48
email          49
age            97
city           56
created_at      0
dtype: int64

In [24]:
products_df.isna().sum()

product_id       0
product_name     0
category         4
price           15
stock            4
dtype: int64

In [25]:
orders_df.isna().sum()

order_id         0
customer_id    569
product_id     560
quantity       594
order_date     603
dtype: int64

## Duplicated Values

In [27]:
customers_df.duplicated().sum()

np.int64(80)

In [28]:
products_df.duplicated().sum()

np.int64(20)

In [29]:
orders_df.duplicated().sum()

np.int64(500)

## Unique Values & Value Distribution

In [31]:
products_df["category"].value_counts()

category
Automotive           81
Beauty               77
Grocery              71
Toys                 71
Garden               71
Sports & Outdoors    70
Office Supplies      69
Furniture            69
Pet Supplies         68
Home & Kitchen       65
Electronics          62
Books                61
Clothing             58
Health               51
Music                49
PET SUPPLIES          2
HEALTH                1
Name: count, dtype: int64

In [32]:
orders_df["quantity"].value_counts()

quantity
5      9975
2      9926
1      9792
9      9787
3      9761
6      9749
10     9731
7      9709
4      9651
8      9594
0       620
two     576
-3      119
-5      116
-2      105
-1      101
-4       94
Name: count, dtype: int64

## Relationships Between Datasets

In [33]:
orders_df["customer_id"].isin(
    customers_df["customer_id"]
).all()

np.False_

In [34]:
orders_df["product_id"].isin(
    products_df["product_id"]
).all()

np.False_

## Next Step
Based on the profiling results, the next step is to define the
data cleaning and transformation rules before implementing the ETL pipeline.